<a href="https://colab.research.google.com/github/akash-sardar/DiseasePrediction/blob/main/Disease_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Complete Dataset consists of 2 CSV files . One of them is training and other is for testing your model.

Each CSV file has 133 columns. 132 of these columns are symptoms that a person experiences and last column is the prognosis.

These symptoms are mapped to 42 diseases you can classify these set of symptoms to.

You are required to train your model on training data and test it on testing data

Kaggle link: https://www.kaggle.com/datasets/kaushil268/disease-prediction-using-machine-learning

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [21]:
df_train = pd.read_csv('Training.csv')
df_test = pd.read_csv('Testing.csv')

In [22]:
print('Train shape: ', df_train.shape)
print('Test shape: ', df_test.shape)


Train shape:  (4920, 134)
Test shape:  (42, 133)


In [23]:
li = list(df_train.columns)
print(li)

['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing', 'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting', 'vomiting', 'burning_micturition', 'spotting_ urination', 'fatigue', 'weight_gain', 'anxiety', 'cold_hands_and_feets', 'mood_swings', 'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat', 'irregular_sugar_level', 'cough', 'high_fever', 'sunken_eyes', 'breathlessness', 'sweating', 'dehydration', 'indigestion', 'headache', 'yellowish_skin', 'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes', 'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea', 'mild_fever', 'yellow_urine', 'yellowing_of_eyes', 'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach', 'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision', 'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure', 'runny_nose', 'congestion', 'chest_pain', 'weakness_in_limbs', 'fast_heart_rate', 'pain_during_bow

In [24]:
li_2 = list(df_test.columns)
print(li_2)

['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing', 'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting', 'vomiting', 'burning_micturition', 'spotting_ urination', 'fatigue', 'weight_gain', 'anxiety', 'cold_hands_and_feets', 'mood_swings', 'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat', 'irregular_sugar_level', 'cough', 'high_fever', 'sunken_eyes', 'breathlessness', 'sweating', 'dehydration', 'indigestion', 'headache', 'yellowish_skin', 'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes', 'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea', 'mild_fever', 'yellow_urine', 'yellowing_of_eyes', 'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach', 'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision', 'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure', 'runny_nose', 'congestion', 'chest_pain', 'weakness_in_limbs', 'fast_heart_rate', 'pain_during_bow

In [25]:
li == li_2

False

In [28]:
df_train = df_train[df_test.columns].copy()

In [29]:
df_train.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [30]:
print('Train shape: ', df_train.shape)
print('Test shape: ', df_test.shape)

Train shape:  (4920, 133)
Test shape:  (42, 133)


In [43]:
len(df_train['prognosis'].unique())

41

In [50]:
from sklearn.preprocessing import LabelEncoder
encode = LabelEncoder()
encode.fit(df_train['prognosis'])
classes = enumerate(encode.classes_)
labels = list()

for i, label in classes:
  labels.append((i, label))




In [58]:
df_train['prognosis'] = encode.transform(df_train['prognosis'])
df_test['prognosis'] = encode.transform(df_test['prognosis'])

itching  skin_rash  nodal_skin_eruptions  \
itching               1.000000   0.318158              0.326439   
skin_rash             0.318158   1.000000              0.298143   
nodal_skin_eruptions  0.326439   0.298143              1.000000   
continuous_sneezing  -0.086906  -0.094786             -0.032566   
shivering            -0.059893  -0.065324             -0.022444   
...                        ...        ...                   ...   
inflammatory_nails   -0.061573   0.331087             -0.023073   
blister              -0.061573   0.331087             -0.023073   
red_sore_around_nose -0.061573   0.331087             -0.023073   
yellow_crust_ooze    -0.061573   0.331087             -0.023073   
prognosis            -0.151898  -0.146564             -0.063307   

                      continuous_sneezing  shivering    chills  joint_pain  \
itching                         -0.086906  -0.059893 -0.175905   -0.160650   
skin_rash                       -0.094786  -0.065324 -0.029324    0.171134   
nodal_skin_eruptions            -0.032566  -0.022444 -0.065917   -0.060200   
continuous_sneezing              1.000000   0.608981  0.446238   -0.087351   
shivering                        0.608981   1.000000  0.295332   -0.060200   
...                                   ...        ...       ...         ...   
inflammatory_nails              -0.033480  -0.023073 -0.067765    0.359845   
blister                         -0.033480  -0.023073 -0.067765   -0.061889   
red_sore_around_nose            -0.033480  -0.023073 -0.067765   -0.061889   
yellow_crust_ooze               -0.033480  -0.023073 -0.067765   -0.061889   
prognosis                       -0.237346  -0.202584  0.120786    0.226410   

                      stomach_pain   acidity  ulcers_on_tongue  ...  \
itching                   0.202850 -0.086906         -0.059893  ...   
skin_rash                 0.161784 -0.094786         -0.065324  ...   
nodal_skin_eruptions     -0.032566 -0.032566         -0.022444  ...   
continuous_sneezing      -0.047254 -0.047254         -0.032566  ...   
shivering                -0.032566 -0.032566         -0.022444  ...   
...                            ...       ...               ...  ...   
inflammatory_nails       -0.033480 -0.033480         -0.023073  ...   
blister                  -0.033480 -0.033480         -0.023073  ...   
red_sore_around_nose     -0.033480 -0.033480         -0.023073  ...   
yellow_crust_ooze        -0.033480 -0.033480         -0.023073  ...   
prognosis                -0.091363  0.058592         -0.050646  ...   

                      blackheads  scurring  skin_peeling  silver_like_dusting  \
itching                -0.059893 -0.059893     -0.061573            -0.061573   
skin_rash               0.320859  0.320859      0.331087             0.331087   
nodal_skin_eruptions   -0.022444 -0.022444     -0.023073            -0.023073   
continuous_sneezing    -0.032566 -0.032566     -0.033480            -0.033480   
shivering              -0.022444 -0.022444     -0.023073            -0.023073   
...                          ...       ...           ...                  ...   
inflammatory_nails     -0.023073 -0.023073      0.946120             0.946120   
blister                -0.023073 -0.023073     -0.023720            -0.023720   
red_sore_around_nose   -0.023073 -0.023073     -0.023720            -0.023720   
yellow_crust_ooze      -0.023073 -0.023073     -0.023720            -0.023720   
prognosis              -0.227907 -0.227907      0.195249             0.195249   

                      small_dents_in_nails  inflammatory_nails   blister  \
itching                          -0.061573           -0.061573 -0.061573   
skin_rash                         0.331087            0.331087  0.331087   
nodal_skin_eruptions             -0.023073           -0.023073 -0.023073   
continuous_sneezing              -0.033480           -0.033480 -0.033480   
shivering                        -0.023073           -0.023073 -0.023073   

In [66]:
df_train.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [68]:
df_train.isnull().values.any()

False

In [84]:
X = df_train.to_numpy()
X[0]

array([ 1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 15])

In [85]:
y = X[:,-1]
y

array([15, 15, 15, ..., 38, 35, 27])

In [86]:
X = X[:,0:-1]

In [92]:
print(X.shape)
print(y.shape)

(4920, 132)
(4920,)


In [93]:
df_test.isnull().values.any()

False

In [94]:
X_test = df_test.to_numpy()
X_test[0]

array([ 1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 15])

In [95]:
y_test = X_test[:,-1]
X_test = X_test[:,0:-1]
print(X_test.shape)
print(y_test.shape)

(42, 132)
(42,)


In [96]:
!pip install Xgboost

In [103]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, f1_score


In [104]:
X_train = X
y_train = y
xgb = XGBClassifier()
rf = RandomForestClassifier()
lr = LogisticRegression()

for i, model in enumerate([xgb, rf, lr]):
  model.fit(X_train, y_train)
  yhat = model.predict(X_train)
  print('Accuracy Score for model ',i,' is ', accuracy_score(yhat, y_train))





Accuracy Score for model  0  is  1.0
Accuracy Score for model  1  is  1.0
Accuracy Score for model  2  is  1.0


In [105]:
for i, model in enumerate([xgb, rf, lr]):
  yhat = model.predict(X_test)
  print('Accuracy Score for model ',i,' is ', accuracy_score(yhat, y_test))

Accuracy Score for model  0  is  0.9761904761904762
Accuracy Score for model  1  is  0.9761904761904762
Accuracy Score for model  2  is  1.0


Accuracy Score for model  0  is  0.9761904761904762
Accuracy Score for model  1  is  0.9761904761904762
Accuracy Score for model  2  is  1.0